### ISSUE TITLE
Fix Windows builds

### ISSUE THREAD

**Issue by Tobias-Fischer** [conda-forge/libsdformat-feedstock#9]
Issue:
After Ruby has been removed from the Windows CI (see https://github.com/conda-forge/conda-forge-ci-setup-feedstock/issues/103#issuecomment-635515749), the Windows builds fail (see https://github.com/conda-forge/libsdformat-feedstock/pull/8). A conda Ruby build does not seem to be appearing any time soon (https://github.com/conda-forge/ruby-feedstock/pull/30).

Options:
- No Windows builds for a while
- Pushing https://github.com/conda-forge/ruby-feedstock/pull/30 forward
- Putting the Azure Ruby back in the path (ideally separately from the other pre-installed stuff which might interfere)

**Comment by Tobias-Fischer** [comment]
I think we can simply re-add the Ruby exe to the path, as specified here: https://docs.microsoft.com/en-us/azure/devops/pipelines/ecosystems/ruby?view=azure-devops#use-a-specific-ruby-version

The versions available are listed here: https://github.com/actions/virtual-environments/blob/master/images/win/Windows2016-Readme.md

**Comment by wolfv** [comment]
but we would have to do this in the conda-forge-ci-setup ideally, right?

**Comment by Tobias-Fischer** [comment]
Ideally yes .. however we could add the build step just in this repo to start with, although it would be a hack.
